name: Outgrow Pipeline Action

on:
  push:
    branches: [ "qa","development", "staging","main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
    - name: Set up Android SDK and NDK
      uses: actions/setup-android@v2
      with:
        android-sdk-version: 30
        android-ndk-version: 21.0.6113669
    - name: Set up environment variables
      run: echo "ANDROID_HOME=${{ env.ANDROID_HOME }}" >> ~/.bashrc && echo "ANDROID_NDK_HOME=${{ env.ANDROID_NDK_HOME }}" >> ~/.bashrc
    - name: Clean project
      run: ./gradlew clean
    - name: Build project
      run: ./gradlew build
    - name: Run tests
      run: ./gradlew test
