name: Outgrow Pipeline Action

on:
  push:
    branches: [ "qa","development", "staging","main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - name: Set up Android SDK and NDK
      uses: android-actions/setup-android@v2
    - name: Set up environment variables
      run: echo "ANDROID_HOME=${{ env.ANDROID_HOME }}" >> ~/.bashrc && echo "ANDROID_NDK_HOME=${{ env.ANDROID_NDK_HOME }}" >> ~/.bashrc
    - name: Touch local properties
      run: touch local.properties
    - name: Add Api Key
      run: echo "apiKey=\"\"" >> local.properties
    - name: Clean project
      run: ./gradlew clean
    - name: Build project
      run: ./gradlew build
    - name: Run tests
      run: ./gradlew test
